name: Build and Deploy WebGL

on:
  push:
    branches:
      - fix_cd
    paths:
      - 'UniTrip/Assets/**'
      - 'UniTrip/Packages/**'
      - 'UniTrip/ProjectSettings/**'
      - '.github/workflows/**'
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - 'UniTrip/Assets/**'
      - 'UniTrip/Packages/**'
      - 'UniTrip/ProjectSettings/**'
      - '.github/workflows/**'
      
jobs:
  build-webgl:
    name: Build WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL
          restore-keys: Library-
          
      - name: Clean up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          docker system prune -af
      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildName: WebGL
          buildsPath: build

      - name: Upload WebGL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-WebGL
          path: build/WebGL
  deploy:
    name: Deploy WebGL to GitHub Pages
    needs: build-webgl
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download WebGL artifact
        uses: actions/download-artifact@v4
        with:
          name: Build-WebGL
          path: build/WebGL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: build/WebGL