name: Build and Deploy WebGL

on:
  push:
    branches:
      - main

jobs:
  buildAndDeploy:
    name: Build and Deploy WebGL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ./UniTrip
          unityVersion: 2022.3.32f1
          testMode: editmode
          artifactsPath: artifacts
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: UnityTestResults
          path: artifacts
      - name: Report Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unity Tests
          path: artifacts/*.xml
          reporter: java-junit

      - name: Build with Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2022.3.32f1
          targetPlatform: WebGL
          projectPath: ./UniTrip

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./UniTrip/Build/WebGL/WebGL
          publish_branch: gh-pages