name: Unity EditMode Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  editmode-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Unity
        uses: actions/cache@v4
        with:
          path: ~/.unity
          key: ${{ runner.os }}-unity

      - name: Setup Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.0f1

      - name: Run EditMode tests
        uses: game-ci/unity-test-runner@v2
        with:
          testMode: EditMode
          unityVersion: 2022.3.0f1
          artifactsPath: test-results

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: EditMode Test Results
          path: test-results